require_relative './config/environment'
require 'sinatra/activerecord/rake'

  # This line turns on logging of the SQL generated by Active Record
  
  # Open a Pry session
  desc "Start the server"
task :server do
  exec "rerun -b 'rackup config.ru'"
end
